import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Dummy from '@/components/dummy'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src='/testfile.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
        <h2 className={styles.heading}>Hunting Coder</h2>
        {/* <Image src="/firosnv-photography-1wBmbnvv4TE-unsplash.jpg" className={styles.image} alt="" width={400} height={200}></Image> */}
        <img src="/firosnv-photography-1wBmbnvv4TE-unsplash.jpg" className={styles.image} alt="code hunting" width={400} height={200} />
        <br />
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Maxime pariatur fugiat asperiores est quas quo maiores numquam officiis, delectus error ab expedita dolor consequuntur tempora tempore omnis beatae quia a nam atque similique! Quae, ut omnis nesciunt ex quia commodi aliquam natus alias eius ea dolorem quos consectetur quam nulla.</p>
        <br />
        <Dummy></Dummy>

      </main>
    </>
  )
}
